package io.agrest.cayenne.cayenne.main.auto;

import java.io.Serializable;

import org.apache.cayenne.EmbeddableObject;
import org.apache.cayenne.Persistent;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.StringProperty;

/** 
 * Embeddable class _E37EmbeddedClass was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually, 
 * since it may be overwritten next time code is regenerated. 
 * If you need to make any customizations, please use subclass. 
 */
public abstract class _E37EmbeddedClass implements EmbeddableObject, Serializable {

    public static final StringProperty<String> CITY = PropertyFactory.createString("city", String.class);
    public static final StringProperty<String> STREET = PropertyFactory.createString("street", String.class);

    // special properties injected by Cayenne
    private Persistent owner;
    private String embeddedProperty;
    
    // declared properties
    protected String city;
    protected String street;

    // lifecycle methods
    protected void propertyWillChange(String property, Object oldValue, Object newValue) {
        if (owner != null && owner.getObjectContext() != null) {
            owner.getObjectContext().propertyChanged(
                    owner,
                    embeddedProperty + "." + property,
                    oldValue,
                    newValue);
        }
    }

    // declared getters and setters
    public void setCity(String city) {
        propertyWillChange("city", this.city, city);
        this.city = city;
    }
    public String getCity() {
        return city;
    }

    public void setStreet(String street) {
        propertyWillChange("street", this.street, street);
        this.street = street;
    }
    public String getStreet() {
        return street;
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "city":
                return this.city;
            case "street":
                return this.street;
            default:
                return null;
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "city":
                this.city = (String)val;
                break;
            case "street":
                this.street = (String)val;
                break;
            default:
                throw new IllegalArgumentException("Unknown property: " + propName);
        }
    }
}
